[battery]
charging_symbol = "⚡️ "
discharging_symbol = "💀 "
full_symbol = ""

[[battery.display]]
style = "bold red"
threshold = 30

[character]
error_symbol = "[😓 ](bold red)"
success_symbol = "[🚀 ](bold fg:50)"

[cmd_duration]
format = " [$duration]($style)"
min_time = 5_000

[directory]
format = " [$path]($style)[$lock_symbol]($lock_style) "
read_only = " "
style = "bold blue"
truncation_length = 5

[git_branch]
format = '\[[$symbol$branch]($style)\]'

[git_commit]
commit_hash_length = 8
style = "bold orange"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\)'

[git_status]
ahead = " x${count} (bold blue) "
behind = "🐢x${count} (bold purple) "
conflicted = " ﲅ (bold red)"
deleted = "﫧x${count} "
diverged = "     x${ahead_count} 🐢x${behind_count} "
format = '\[$all_status$ahead_behind\]'
modified = "📝x${count} "
renamed = " x${count} "
staged = " x${count} "
stashed = "📦 "
untracked = "x${count} "

[hostname]
disabled = false
format = "[$hostname]($style)"
ssh_only = false
style = "bold dimmed red"
trim_at = "-"

[memory_usage]
format = '\[$symbol[$ram( | $swap)]($style)\]'

[package]
format = '\[[$symbol$version]($style)\]'

[nodejs]
format = '\[[$symbol($version)]($style)\]'

[cmake]
format = '\[[$symbol($version)]($style)\]'

[perl]
format = '\[[$symbol($version)]($style)\]'

[lua]
format = '\[[$symbol($version)]($style)\]'

[python]
format = '\[[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style)\]'

[ruby]
format = '\[[$symbol($version)]($style)\]'

[rust]
format = '\[[$symbol($version)]($style)\]'

[golang]
format = '\[[$symbol($version)]($style)\]'

[php]
format = '\[[$symbol($version)]($style)\]'

[scala]
format = '\[[$symbol($version)]($style)\]'

[nix_shell]
format = '\[[$symbol$state( \($name\))]($style)\]'

[julia]
format = '\[[$symbol($version)]($style)\]'

[java]
format = '\[[$symbol($version)]($style)\]'

[docker_context]
format = '\[[$symbol$context]($style)\]'

[aws]
format = '\[[$symbol($profile)(\($region\))(\[$duration\])]($style)\]'

[conda]
format = '\[[$symbol$environment]($style)\]'

[dart]
format = '\[[$symbol($version)]($style)\]'

[time]
disabled = true
format = "$time($style) "
style = "dimmed green"
time_format = "%T"

[username]
show_always = true
style_user = "bold blue"
