# Dracula theme for Alacritty
# https://draculatheme.com/alacritty
#
# Color palette
# https://spec.draculatheme.com
#
# Instructions
# https://github.com/alacritty/alacritty/blob/master/extra/man/alacritty.5.scd

[colors.primary]
background = "#282a36"
bright_foreground = "#ffffff"
foreground = "#f8f8f2"

[colors.cursor]
cursor = "#f8f8f2"
text = "#282a36"

[colors.vi_mode_cursor]
cursor = "CellForeground"
text = "CellBackground"

[colors.selection]
background = "#44475a"
text = "CellForeground"

[colors.normal]
black = "#21222c"
blue = "#bd93f9"
cyan = "#8be9fd"
green = "#50fa7b"
magenta = "#ff79c6"
red = "#ff5555"
white = "#f8f8f2"
yellow = "#f1fa8c"

[colors.bright]
black = "#6272a4"
blue = "#d6acff"
cyan = "#a4ffff"
green = "#69ff94"
magenta = "#ff92df"
red = "#ff6e6e"
white = "#ffffff"
yellow = "#ffffa5"

[colors.search.matches]
background = "#50fa7b"
foreground = "#44475a"

[colors.search.focused_match]
background = "#ffb86c"
foreground = "#44475a"

[colors.footer_bar]
background = "#282a36"
foreground = "#f8f8f2"

[colors.hints.start]
background = "#f1fa8c"
foreground = "#282a36"

[colors.hints.end]
background = "#282a36"
foreground = "#f1fa8c"
