#!/bin/env bash

#####################################################
# ______  ___________ _    ____  ___
# | ___ \/  ___| ___ \ |  | |  \/  |
# | |_/ /\ `--.| |_/ / |  | | .  . |
# | ___ \ `--. \  __/| |/\| | |\/| |
# | |_/ //\__/ / |   \  /\  / |  | |
# \____/ \____/\_|    \/  \/\_|  |_/
#
#####################################################
source "$HOME/.cache/wal/colors.sh"
THIRD_MONITOR=$(xrandr -q | grep 'DisplayPort-[0-9] connected' | awk '{print $1}')

##############################
# AUTOSTART
##############################
pgrep -x sxhkd > /dev/null || sxhkd &

#POLYBAR
~/.config/polybar/scripts/launch.sh

##############################
# MONITORS
##############################
bspc monitor eDP -d 11 12 13 14 15
bspc monitor HDMI-A-0 -d 1 2 3 4 5
bspc monitor "$THIRD_MONITOR" -d 6 7 8 9 10
bspc config remove_disabled_monitors  true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

##############################
# COLORS
##############################
bspc config focused_border_color "$color9"
bspc config normal_border_color "$color12"
bspc config active_border_color "$color12"

##############################
# BSPWM CONFIGURATIONS
##############################
bspc config border_width         1
bspc config borderless_monocle   false
bspc config window_gap            20
bspc config split_ratio           0.50
bspc config gapless_monocle       true
bspc config focus_follows_pointer true
bspc config center_pseudo_tiled true
bspc config directional_focus_tightness low
bspc config top_padding 25
# bspc config ignore_ewmh_fullscreen entert

##############################
# WINDOW RULES
##############################
bscp rule -r "*"
bspc rule -a '*' rectangle="1800x1200+0+0" center=true
bspc rule -a Pacfinder rectangle="1800x1200+0+0" state=floating center=true
bspc rule -a Nsxiv state=floating rectangle="1000x1000+0+0" center=true
bspc rule -a Timeshift-gtk state=floating rectangle="1000x1000+0+0" center=true
bspc rule -a feh state=floating rectangle="1000x1000+0+0" center=true
bspc rule -a Xfce4-power-manager-settings state=floating center=true
bspc rule -a Gpick state=floating center=true
bspc rule -a Pavucontrol state=floating center=true
bspc rule -a Lxappearance state=floating rectangle="1000x1000+0+0" center=true
bspc rule -a Wpg state=floating rectangle="1000x1000+0+0" center=true
bspc rule -a Slack:slack desktop=^10 state=tiled
bspc rule -a Gimp-2.10 state=floating rectangle="1800x1200+0+0" center=true
bspc rule -a Thunar:thunar state=floating rectangle="1800x1200+0+0" center=true
bspc rule -a Thunar:thunar:'File Operation Progress' state=floating rectangle="800x600+0+0" center=true
bspc rule -a Evince state=floating rectangle="1800x1200+0+0" center=true
bspc rule -a Nm-connection-editor state=floating rectangle="1800x1200+0+0" center=true
bspc rule -a Virt-manager state=floating rectangle='1200x1000+0+0' center=true
bspc rule -a Dconf-editor state=floating rectangle="1200x1000+0+0" center=true
bspc rule -a SpeedCrunch state=floating rectangle="1060x750+0+0" center=true
bspc rule -a LVIM:lvim state=fullscreen
bspc rule -a firefox:Devtools state=floating rectangle="1800x1200+0+0" center=true
bspc rule -a polkit-kde-authentication-agent-1 state=floating rectangle="400x300+0+0" center=true
