#!/bin/env bash

#############
# AUTOSTART #
#############
pgrep -x sxhkd >/dev/null || sxhkd &
~/.config/polybar/scripts/launch.sh

############
# MONITORS #
############
bspc monitor DisplayPort-0 -d 1 2 3 4 5
bspc monitor DisplayPort-1 -d 6 7 8 9 10
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bpsc config merge_overlapping_monitors true

##########
# COLORS #
##########
bspc config focused_border_color "#9ECE6A"
bspc config normal_border_color "#FF9E64"
bspc config active_border_color "#7DCFFF"

###########
# CONFIGS #
###########
bspc config border_width 2
# bspc config ignore_ewmh_fullscreen all
bspc config borderless_monocle false
bspc config window_gap 20
bspc config split_ratio 0.50
bspc config gapless_monocle true
bspc config focus_follows_pointer true
bspc config center_pseudo_tiled true
bspc config directional_focus_tightness low
# Padding ideally should match your polybar height value
bspc config top_padding 35

#########
# RULES #
#########
# class:instance:title
bspc rule -r "*"
bspc rule -a '*' rectangle="1800x1200+0+0" center=true
bspc rule -a Slack:*:* desktop=10 state=tiled # Make sure to toggle full screen in the application
bspc rule -a Pacfinder rectangle="1800x1200+0+0" state=floating center=true
bspc rule -a Timeshift-gtk state=floating rectangle="1000x1000+0+0" center=true
bspc rule -a feh:feh state=floating rectangle="1800x1200+0+0" center=true
bspc rule -a Nsxiv:nsxiv state=floating rectangle="1800x1200+0+0" center=true
bspc rule -a Qalculate-gtk:qalculate-gtk state=floating rectangle="1800x1200+0+0" center=true
bspc rule -a Xfce4-power-manager-settings state=floating center=true
bspc rule -a Gpick state=floating center=true
bspc rule -a Pavucontrol state=floating center=true
bspc rule -a Lxappearance state=floating rectangle="1800x1200+0+0" center=true
bspc rule -a Wpg state=floating rectangle="1000x1000+0+0" center=true
bspc rule -a copyq:copyq state=floating rectangle="1000x1000+0+0" center=true
bspc rule -a Gimp-2.10 state=floating rectangle="1800x1200+0+0" center=true
bspc rule -a Evince state=floating rectangle="1800x1200+0+0" center=true
bspc rule -a Nm-connection-editor state=floating rectangle="1800x1200+0+0" center=true
bspc rule -a Virt-manager state=floating rectangle='1200x1000+0+0' center=true
bspc rule -a Dconf-editor state=floating rectangle="1200x1000+0+0" center=true
bspc rule -a 'File-roller' state=floating rectangle="1200x1000+0+0" center=true
bspc rule -a SpeedCrunch state=floating rectangle="1060x750+0+0" center=true
bspc rule -a firefox:Devtools state=floating rectangle="1800x1200+0+0" center=true
bspc rule -a "polkit-dumb-agent":"polkit-dumb-agent" state=pseudo_tiled rectangle="400x300+0+0" center=true
bspc rule -a "cataclysm-tiles":"cataclysm-tiles" state=fullscreen
bspc rule -a "*:*:Open File" state=floating rectangle="1200x800+0+0" center=true
bspc rule -a "scratchpad_term:scratchpad_term:scratchpad_term" state=floating rectangle="2300x1000+0+0" sticky=true center=true
bspc rule -a "bspwm_scpad_nvim:bspwm_scpad_nvim:bspwm_scpad_nvim" state=tiled sticky=true
bspc rule -a "bspwm_scpad_btop:bspwm_scpad_btop:bspwm_scpad_btop" state=floating rectangle="2300x1000+0+0" sticky=true center=true
bspc rule -a "bspwm_scpad_ranger:bspwm_scpad_ranger:bspwm_scpad_ranger" state=floating rectangle="2300x1000+0+0" sticky=true center=true
bspc rule -a "*:*:cava" state=floating rectangle="1200x800+1200+300" center=false
bspc rule -a "*:*:ncmpcpp" state=floating rectangle="1000x500+100+100" center=false
bspc rule -a "*:*:pipes" state=floating rectangle="1000x500+100+800" center=false
bspc rule -a "steam:steamwebhelper:Steam - Browser" state=floating rectangle="1800x1200+0+0" center=true
bspc rule -a "dosbox-staging" state=tiled desktop=8
bspc rule -a "ck3:ck3" state=tiled desktop=8
bspc rule -a "Project Zomboid:Project Zomboid" state=tiled desktop=8
bspc rule -a "stellaris:stellaris" state=fullscreen desktop=8
bspc rule -a "*:*:Sins of a Solar Empire: Rebellion" state=fullscreen desktop=8
bspc rule -a "*:*:Homeworld Remastered" state=fullscreen desktop=8
bspc rule -a "*:*:Stardock Launcher" state=floating desktop=8

bspc config external_rules_command "$HOME/.config/bspwm/external_rules"
