#!/usr/bin/env bash

wid=$1
class=$2
instance=$3
title=$(xdotool getwindowname "$wid")
# Associative Array https://linuxhint.com/associative_array_bash/

small_screen="state=floating rectangle='400*400+0+0' center=true"

declare -A title_arr=(
    ["Confirm to replace files"]=1
    ["File Operation Progress"]=1
    ["Terminator Preferences"]=1
    ["Choose Terminal Text Color"]=1
    ["Choose Palette Color"]=1
    ["Create New Folder"]=1
    ["Attention"]=1
    ["New Empty File..."]=1
    ["Empty Trash"]=1
)

if [[ "$class" == "Terminator" || "$class" == "Thunar" || "$instance" == "Terminator" || "$instance" == "Thunar" ]]; then
    [[ -z "$title" ]] && echo "$small_screen"
fi

[[ -n "${title_arr[$title]}" || "$title" == "Rename"* ]] && echo "$small_screen"

[[ "$title" == "Steam" || "$title" = "Steam - News" ]] && echo "desktop=7"

[[ "$title" = "Dwarf Fortress" ]] && echo "desktop=8"

[[ "$title" = "Steam - News" ]] && echo "state=floating"
[[ "$class" == "Steam" && $title == "Friends List" ]] && echo "state=floating desktop=7 rectangle=700x700+0+0"

[[ "$title" = "Z:\home\sam\.local\share\Steam\steamapps\common\Dwarf Fortress\Dwarf Fortress.exe" ]] && echo "state=floating desktop=7 rectangle=100x100+0+0"

{
    echo "CLASS: $class"
    echo "INSTANCE: $instance"
    echo "TITLE: $title"
} >>/tmp/external_rules
