[module/pulseaudio]
type = internal/pulseaudio

format-volume            = <ramp-volume><label-volume>
format-volume-foreground = ${colors.color8}
format-volume-background = ${colors.foreground}
label-volume             = %{T1}%percentage%%
label-volume-padding     = 1
label-volume-foreground = ${colors.color8}
format-muted-foreground     = ${colors.color1}
format-muted-background     = ${self.format-volume-background}
format-muted-prefix         = %{T1}婢
format-muted-prefix-padding = 1
label-muted                 = Muted
label-muted-padding         = ${self.label-volume-padding}

# Quick note - currently pulseaudio and pavu are maxing out at 153% for me.
ramp-volume-0 =%{T1}奄
ramp-volume-1 =%{T1}奄
ramp-volume-2 =%{T1}奔
ramp-volume-3 =%{T1}奔
ramp-volume-4 =%{T1}墳
ramp-volume-5 =%{T1}墳
ramp-volume-6 =%{T1}
ramp-volume-padding = 1

click-right = pavucontrol