[module/pulseaudio]
type = internal/pulseaudio
interval = 2

format-volume               = <ramp-volume><label-volume>
format-volume-foreground    = ${colors.color8}
format-volume-background    = ${colors.foreground6}
label-volume                = %{T0}%percentage%%
label-volume-padding        = 1
label-volume-foreground     = ${colors.color8}
format-muted-foreground     = ${colors.color1}
format-muted-background     = ${self.format-volume-background}
format-muted-prefix-padding = 1
label-muted                 = %{T1}🔇 muted
label-muted-padding         = ${self.label-volume-padding}

# Quick note - currently pulseaudio and pavu are maxing out at 153% for me.
ramp-volume-0 = %{T1}🔈
ramp-volume-1 = %{T1}🔉
ramp-volume-2 = %{T1}🔊

ramp-volume-padding = 1

click-right = pavucontrol